//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposersLibrary_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLibraryEntities1 : DbContext
    {
        public DBLibraryEntities1()
            : base("name=DBLibraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPOSER> COMPOSERs { get; set; }
        public virtual DbSet<PERFORMANCE> PERFORMANCEs { get; set; }
        public virtual DbSet<PERFORMER> PERFORMERs { get; set; }
        public virtual DbSet<SONG> SONGs { get; set; }
        public virtual DbSet<SONG_COLLECTION> SONG_COLLECTION { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<СSONG> СSONG { get; set; }
    }
}
