//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposersLibrary_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFORMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERFORMER()
        {
            this.PERFORMANCEs = new HashSet<PERFORMANCE>();
        }
    
        public int PF_ID { get; set; }
        public string PF_NAME { get; set; }
        public Nullable<System.DateTime> PF_DATE_OF_BIRTH { get; set; }
        public string PF_NATIONALITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCE> PERFORMANCEs { get; set; }
    }
}
