//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposersLibrary_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFORMANCE
    {
        public int PRF_ID { get; set; }
        public int PRF_PERFORMER_ID { get; set; }
        public int PRF_SONG_ID { get; set; }
        public string PRF_NAME { get; set; }
        public Nullable<System.DateTime> PRF_DATE { get; set; }
        public string PRF_PLACE { get; set; }
    
        public virtual PERFORMER PERFORMER { get; set; }
        public virtual SONG SONG { get; set; }
    }
}
